#!/bin/bash	
#interface

seleccion=$(zenity --list \
	  --title="Escoge la funcion que quieras usar" \
	  --width=600 \
	  --height=250 \
	  --column="Numero" --column="Funcion" --column="Descripcion" \
	    1 "Conexion Remota" "Conexion via ssh con otro ordenador" \
	    2 "Buscador"  "Busqueda de texto en archivo,archivos, grupos usuarios" \
	    3 "Servicios" "Manejador de servicios,firewall, scanner de dispositivos" \
	    4 "Comandos por voz" "Reconocedor de comandos via voz " )

if [[ $seleccion == "1" ]]
then
	respuesta=$(zenity --forms --title="Conexion remota" \
			--text="Ingrese los datos de la otra maquinapara realizar la conexion" \
			--separator="," \
			--add-entry="Nombre de usuario" \
			--add-entry="Ip " \
			--add-password="Contrasena" )
	username=$(cut -d "," -f 1 <<< $respuesta)
	ipDir=$(cut -d "," -f 2 <<< $respuesta)
	password=$(cut -d "," -f 3 <<< $respuesta)
	#session=$(./remote_access/access $username $ipDir $password)
	./remote_access/access $username $ipDir $password
	#gnome-terminal --window-with-profile=NOCLOSEPROFILE -e $session
	exit
fi


if [[ $seleccion == "2" ]]
then
	task=$(zenity --list \
	  --title="Que es lo quieres hacer?" \
	  --column="Function"  \
	   "Buscar texto en un archivo" \
	   "Busqueda de archivos en un directorio" \
	   "Busqueda de grupos" \
	   "Busqueda de usuarios"\
	--width=300 \
	--height=300 )	
case $task in
	"Buscar texto en un archivo")
		./searchs/interfaceFindText.sh
	;;
	"Busqueda de archivos en un directorio")
		./searchs/interfaceFileSearch
	;;
	"Busqueda de grupos")
		./searchs/interfaceFindGroup.sh
	;;
	"Busqueda de usuarios")
		./searchs/interfaceFindUser.sh
	;;
	*)
		echo "Codigo fallido"
	;;
esac

exit

fi

if [[ $seleccion == "3" ]]
then
	task=$(zenity --list \
	  --title="Que es lo quieres hacer?" \
	  --column="Function"  \
	   "Manejar servicios" \
	   "Firewall" \
	   "Quienes estan en mi red?" \
	--width=300 \
	--height=300 )
case $task in
	"Manejar servicios")
		./services/interfaceServices
	;;
	"Firewall")
		./services/interfaceFirewall.sh
	;;
	"Quienes estan en mi red?")
		./services/identify.sh
	;;
	*)
		echo "Codigo fallido"
	;;
esac

	exit
fi


if [[ $seleccion == "4" ]]
then
	./voice_commands/main_voice.sh >/dev/null 2>/dev/null
	exit
fi
